function init(self)
	-- sends a message to the camera ganeobject to aqquire an input for it to follow
	msg.post("#camera", "acquire_camera_focus")
end

-- when the camea recieves a message and the message id is "follow" set the camera to follow whatever
-- sent the message but -400x and -700y away from the centre
function on_message(self, message_id, message, sender)
	if message_id == hash("follow") then 
		go.set_parent(".", sender) 
		go.set_position(vmath.vector3(-400, -900, 0))
	end
end